# Generated by Django 4.1.6 on 2023-07-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbuzz', '0002_post_follower_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='context_image',
            new_name='content_image',
        ),
    ]
